In [39]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import tensorflow as tf

In [40]:
with open('label_encoder.pkl','rb') as file : 
    label_encoder=pickle.load(file)

In [41]:
with open('onehot_encoder.pkl','rb') as file : 
    onehot=pickle.load(file)

In [42]:
with open('scalar.pkl','rb') as file : 
    scaler=pickle.load(file)

In [43]:
model=load_model('titanic_model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [44]:
user={'Pclass':3,'Sex':'male','SibSp':1,'Parch':0,'Fare':11,'Embarked':'Queenstown'}

In [45]:
user=pd.DataFrame([user])

In [46]:
user.head()

   Pclass   Sex  SibSp  Parch  Fare    Embarked
0       3  male      1      0    11  Queenstown

In [47]:
user['Sex']=label_encoder.transform(user['Sex'])

In [48]:
user

   Pclass  Sex  SibSp  Parch  Fare    Embarked
0       3    1      1      0    11  Queenstown

In [49]:
embarked=onehot.transform(user[['Embarked']])

In [50]:
embarked=pd.DataFrame(embarked,columns=onehot.get_feature_names_out())

In [51]:
embarked

   Embarked_Cherbourg  Embarked_Queenstown  Embarked_Southampton
0                 0.0                  1.0                   0.0

In [52]:
user=pd.concat([user,embarked],axis=1).drop('Embarked',axis=1)

In [53]:
user[['Pclass','SibSp','Parch','Fare']]=scaler.transform(user[['Pclass','SibSp','Parch','Fare']])

In [54]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,0.824079,1,0.471558,-0.463961,-0.45758,0.0,1.0,0.0

In [55]:
y=model.predict(user)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

In [57]:
y=y[0][0]

In [58]:
y

np.float32(0.30020094)

In [59]:
if y>0.5:
    print("The passenger is likely to survive.")
else:
    print("The passenger is likely to not survive.")

The passenger is likely to not survive.