In [50]:
import pandas as pd

In [51]:
df=pd.read_csv('huge_1M_titanic.csv')

In [52]:
df=df.sample(10000)

In [53]:
df.shape

(10000, 12)

In [54]:
df.info()

<class 'pandas.DataFrame'>
Index: 10000 entries, 244889 to 221637
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  10000 non-null  int64
 1   Survived     10000 non-null  int64
 2   Pclass       10000 non-null  int64
 3   Name         10000 non-null  str
 4   Sex          10000 non-null  str
 5   Age          7970 non-null   float64
 6   SibSp        10000 non-null  int64
 7   Parch        10000 non-null  int64
 8   Ticket       10000 non-null  str
 9   Fare         10000 non-null  float64
 10  Cabin        2257 non-null   str
 11  Embarked     9972 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 1015.6 KB

In [55]:
df.isnull().sum()

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age            2030
SibSp             0
Parch             0
Ticket            0
Fare              0
Cabin          7743
Embarked         28
dtype: int64

In [56]:
df=df.drop(columns=['Cabin','PassengerId','Name','Ticket','Age'])

In [57]:
df.head()

        Survived  Pclass     Sex  SibSp  Parch        Fare Embarked
244889         0       2    male      0      0   37.743545        S
964243         0       1  female      3      2  200.202333        S
469583         0       3  female      1      0   12.668934        S
360030         1       3    male      0      0    0.000000        C
933535         0       3    male      3      1   24.593393        S

In [58]:
df['Embarked'].value_counts()

Embarked
S    7298
C    1863
Q     811
Name: count, dtype: int64

### DATA CLEANING

In [59]:
df['Embarked']=df['Embarked'].replace({'S':'Southampton','C':'Cherbourg','Q':'Queenstown'})

In [60]:
df.head()

        Survived  Pclass     Sex  SibSp  Parch        Fare     Embarked
244889         0       2    male      0      0   37.743545  Southampton
964243         0       1  female      3      2  200.202333  Southampton
469583         0       3  female      1      0   12.668934  Southampton
360030         1       3    male      0      0    0.000000    Cherbourg
933535         0       3    male      3      1   24.593393  Southampton

In [61]:
df.dropna(subset=['Embarked'],inplace=True)

In [62]:
df.head()

        Survived  Pclass     Sex  SibSp  Parch        Fare     Embarked
244889         0       2    male      0      0   37.743545  Southampton
964243         0       1  female      3      2  200.202333  Southampton
469583         0       3  female      1      0   12.668934  Southampton
360030         1       3    male      0      0    0.000000    Cherbourg
933535         0       3    male      3      1   24.593393  Southampton

In [63]:
df['Embarked'].value_counts()

Embarked
Southampton    7298
Cherbourg      1863
Queenstown      811
Name: count, dtype: int64

In [64]:
df['Fare']=df['Fare'].astype('int')

In [65]:
df.head()

        Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
244889         0       2    male      0      0    37  Southampton
964243         0       1  female      3      2   200  Southampton
469583         0       3  female      1      0    12  Southampton
360030         1       3    male      0      0     0    Cherbourg
933535         0       3    male      3      1    24  Southampton

## Feature Enconding

#### Encode - Gender -> Label encoder
#### Embarked -> One hote encoding

In [66]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [67]:
df['Sex']=le.fit_transform(df['Sex'])

In [68]:
df.head()

        Survived  Pclass  Sex  SibSp  Parch  Fare     Embarked
244889         0       2    1      0      0    37  Southampton
964243         0       1    0      3      2   200  Southampton
469583         0       3    0      1      0    12  Southampton
360030         1       3    1      0      0     0    Cherbourg
933535         0       3    1      3      1    24  Southampton

In [69]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
Embarked=ohe.fit_transform(df[['Embarked']])
Embarked=pd.DataFrame(Embarked,columns=ohe.get_feature_names_out())

In [70]:
df.head()

        Survived  Pclass  Sex  SibSp  Parch  Fare     Embarked
244889         0       2    1      0      0    37  Southampton
964243         0       1    0      3      2   200  Southampton
469583         0       3    0      1      0    12  Southampton
360030         1       3    1      0      0     0    Cherbourg
933535         0       3    1      3      1    24  Southampton

In [71]:
Embarked

      Embarked_Cherbourg  Embarked_Queenstown  Embarked_Southampton
0                    0.0                  0.0                   1.0
1                    0.0                  0.0                   1.0
2                    0.0                  0.0                   1.0
3                    1.0                  0.0                   0.0
4                    0.0                  0.0                   1.0
...                  ...                  ...                   ...
9967                 0.0                  0.0                   1.0
9968                 0.0                  0.0                   1.0
9969                 0.0                  0.0                   1.0
9970                 0.0                  0.0                   1.0
9971                 0.0                  0.0                   1.0

[9972 rows x 3 columns]

In [72]:
df=pd.concat([df.drop(columns=['Embarked']),Embarked],axis=1)

In [73]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
244889,0.0,2.0,1.0,0.0,0.0,37.0,NaN,NaN,NaN
964243,0.0,1.0,0.0,3.0,2.0,200.0,NaN,NaN,NaN
469583,0.0,3.0,0.0,1.0,0.0,12.0,NaN,NaN,NaN
360030,1.0,3.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN
933535,0.0,3.0,1.0,3.0,1.0,24.0,NaN,NaN,NaN

### feature scaling

In [74]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()

In [75]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Cherbourg', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype='str')

In [76]:
num_columns=['Pclass', 'SibSp', 'Parch', 'Fare']

In [77]:
df[num_columns]=scale.fit_transform(df[num_columns])

In [78]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
244889,0.0,-0.370530,1.0,-0.459052,-0.463961,0.089884,NaN,NaN,NaN
964243,0.0,-1.565138,0.0,2.332777,2.135994,3.522065,NaN,NaN,NaN
469583,0.0,0.824079,0.0,0.471558,-0.463961,-0.436524,NaN,NaN,NaN
360030,1.0,0.824079,1.0,-0.459052,-0.463961,-0.689200,NaN,NaN,NaN
933535,0.0,0.824079,1.0,2.332777,0.836016,-0.183848,NaN,NaN,NaN

In [79]:
import pickle

In [80]:
with open('label_encoder.pkl','wb') as f:
    pickle.dump(le,f)

In [81]:
with open('onehot_encoder.pkl','wb') as f:
    pickle.dump(ohe,f)

In [82]:
with open('scalar.pkl','wb') as f:
    pickle.dump(scale,f)

In [83]:
df=df.dropna()

### train_test_split

In [84]:
X=df.drop(columns='Survived')

In [85]:
Y=df['Survived']

In [86]:
X.head()

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
327,-1.565138,1.0,-0.459052,-0.463961,-0.541805,0.0,0.0,1.0
9894,-1.565138,0.0,1.402167,-0.463961,0.384673,0.0,0.0,1.0
7521,0.824079,1.0,-0.459052,-0.463961,-0.499693,0.0,1.0,0.0
2635,0.824079,0.0,-0.459052,-0.463961,-0.562862,0.0,0.0,1.0
6122,0.824079,1.0,-0.459052,-0.463961,-0.352299,0.0,0.0,1.0

In [87]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [88]:
x_train,x_valid,y_train,y_valid=train_test_split(x_train,y_train,test_size=0.2,random_state=42)

In [89]:
x_train.shape

(60, 8)

### Model building

In [90]:
%pip install tensorflow

Requirement already satisfied: tensorflow in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.22.0rc0)
Requirement already satisfied: absl-py>=1.0.0 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in C:\Users\SHASHANK\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: six>=1.12.0 in C:\Users\SHASHANK\AppData\Roaming\Python\Python314\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (1.84.0)
Requirement already satisfied: keras-nightly>=3.12.0.dev in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (3.16.0.dev2026100605)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: h5py~=3.15.1 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras-nightly>=3.12.0.dev->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras-nightly>=3.12.0.dev->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras-nightly>=3.12.0.dev->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich->keras-nightly>=3.12.0.dev->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\SHASHANK\AppData\Roaming\Python\Python314\site-packages (from rich->keras-nightly>=3.12.0.dev->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras-nightly>=3.12.0.dev->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [91]:
import tensorflow

In [92]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [93]:
model = Sequential([
    Dense(128, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(64,activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

c:\Users\SHASHANK\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\keras\src\layers\core\dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [94]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,521 (45.00 KB)

 Trainable params: 11,521 (45.00 KB)

 Non-trainable params: 0 (0.00 B)

### Model compilation

In [95]:
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [96]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [97]:
stopping_callback = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [98]:
model.fit(x_train, y_train, validation_data=(x_valid, y_valid), epochs=10, batch_size=32, callbacks=[stopping_callback])

Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 1s/step - accuracy: 0.4833 - loss: 0.7035 - val_accuracy: 0.6875 - val_loss: 0.6729
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.7000 - loss: 0.5443 - val_accuracy: 0.6250 - val_loss: 0.7812
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7833 - loss: 0.4641 - val_accuracy: 0.6250 - val_loss: 0.9234
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.7833 - loss: 0.3908 - val_accuracy: 0.6250 - val_loss: 0.9104
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8167 - loss: 0.3059 - val_accuracy: 0.6875 - val_loss: 0.8899
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.8667 - loss: 0.2527 - val_accuracy: 0.5625 - val_loss: 1.1151

In [99]:
model.save('titanic_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [100]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
327,0.0,-1.565138,1.0,-0.459052,-0.463961,-0.541805,0.0,0.0,1.0
9894,1.0,-1.565138,0.0,1.402167,-0.463961,0.384673,0.0,0.0,1.0
7521,0.0,0.824079,1.0,-0.459052,-0.463961,-0.499693,0.0,1.0,0.0
2635,0.0,0.824079,0.0,-0.459052,-0.463961,-0.562862,0.0,0.0,1.0
6122,1.0,0.824079,1.0,-0.459052,-0.463961,-0.352299,0.0,0.0,1.0

In [101]:
X

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
327,-1.565138,1.0,-0.459052,-0.463961,-0.541805,0.0,0.0,1.0
9894,-1.565138,0.0,1.402167,-0.463961,0.384673,0.0,0.0,1.0
7521,0.824079,1.0,-0.459052,-0.463961,-0.499693,0.0,1.0,0.0
2635,0.824079,0.0,-0.459052,-0.463961,-0.562862,0.0,0.0,1.0
6122,0.824079,1.0,-0.459052,-0.463961,-0.352299,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...
6856,0.824079,0.0,0.471558,0.836016,-0.457580,0.0,0.0,1.0
9392,-1.565138,0.0,0.471558,0.836016,-0.689200,1.0,0.0,0.0
736,-1.565138,1.0,-0.459052,-0.463961,0.174110,0.0,0.0,1.0
9463,0.824079,0.0,3.263387,2.135994,0.721574,0.0,0.0,1.0
7286,0.824079,0.0,0.471558,0.836016,-0.310186,0.0,0.0,1.0